name: Master Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout
      #
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: .
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      #
      # Login to Docker Hub
      #
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # Build
      #
      - name: build the image
        working-directory: ./
        run: |
          docker build --push --no-cache \
            --tag hendrix04/Hatjitsu:latest \
            --build-arg COMMIT=$(git rev-parse HEAD) \
            --platform linux/amd64 .
